db:
  dynamo:
    endpoint_url: http://dynamo:8000
    points_table_name: zephyr-points

dataloader:
  aws:
    source_bucket: essar-zephyr-test
  batch_size: 1000
  head_length: 30
  tail_length: 30

cleanup:
  skip_interpolate: no
  skip_outlyers: no

outlyer:
  max_speed: 100
  max_speed_factor: 3.0
