db:
  dynamo:
    endpoint_url: http://dynamo:8000
    points_table_name: zephyr-points

dataloader:
  aws:
    source_bucket: essar-zephyr-test
  gps:
    convert_coords: Yes

cleanup:
  outlyer_max_speed: 100
  outlyer_max_speed_factor: 3.0
