aws:
  s3:
    source_bucket: essar-zephyr-test

db:
  dynamo:
    endpoint_url: http://dynamo:8000
    points_table_name: zephyr-points

dataloader:
  batch_size: 1000
  head_length: 30
  tail_length: 30

cleanup:
  skip_interpolate: no
  skip_outlyers: no

logging:
  debug: off
  point_log: off

outlyer:
  max_speed: 100
  max_speed_factor: 3.0
